### PR TITLE
fix extended user profile

### PR DESCRIPTION
**Pull request by goldsky**
this commit fixes placeholder creation from the multi dimensional nested containers + attribute of the extended user profile

### CODE REVIEW

**Comment by goldsky** [comment]
e560535 commit is about adding new property, &extendedTpls to the Profile snippet.
This feature deals with multi dimensional array of nested containers inside the extended profile, and solve the problem with dynamic form.
The original snippet only parses the content in one layer, so each of placeholders needs to be called individually, eg:

<pre>
School: [[+education.school.name.0]]
Level: [[+education.school.level.0]]
School: [[+education.school.name.1]]
Level: [[+education.school.level.1]]
</pre>

This commit generates the loop of chunk of a dynamic form.

<h2>Example</h2>

The usage call: <code>[[!Profile? &extendedTpls=`{"education":"educationChunk","work":"workChunk"}`]]</code>
The chunk name "educationChunk" is like this:

<pre><code>    &lt;table&gt;
        &lt;tr&gt;
            &lt;td&gt;School&lt;/td&gt;
            &lt;td&gt;:&lt;/td&gt;
            &lt;td&gt;
                &lt;input
                    type=&quot;text&quot;
                    name=&quot;education[school][name][]&quot;
                    value=&quot;[[+education.school.name.index]]&quot;
                    /&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td&gt;Level&lt;/td&gt;
            &lt;td&gt;:&lt;/td&gt;
            &lt;td&gt;
                &lt;input
                    type=&quot;text&quot;
                    name=&quot;education[school][level][]&quot;
                    value=&quot;[[+education.school.level.index]]&quot;
                    /&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
    &lt;/table&gt;
</code></pre>

Where the resource main page contains this:

<pre><code>    &lt;div id=&quot;education-table&quot;&gt;
        [[+education]]
    &lt;/div&gt;
    &lt;a
        href=&quot;javascript:void(0)&quot;
        onclick=&quot;$('#education-table').append(newEdu)&quot;
        &gt;Add more school
    &lt;/a&gt;
</code></pre>

The <code>[[+education]]</code> placeholder comes from the Ultimate Parent of the nested containers.
Please notice that javascript's dynamic form. The <code>newEdu</code> property contains the above chunk.

With this kind of form, this commit places the MODX's usual habit to loop the row contents into the chunk.

<h3>Persistent Issue</h3>

<u>I still can't find how to deal with checkbox, since when the $_POST is sent, the checkbox's name will not be available if it is not checked.</u>
Can be done with UpdateProfile's preHook.

**Comment by goldsky** [comment]
93f3b28 commit is to move getExtended() method to the parent controller class.
7ffc1cd is to add an API to check whether a set of extended fields is empty or not.
This UpdateProfile's preHook code might give you a glance:

<pre><code>&lt;?php

/* clean ups */
$dob = $hook-&gt;getValue('dob');
$hook-&gt;setValue('dob', strtotime($dob));

$edu = $hook-&gt;getValue('education');
$checkEdu = $hook-&gt;controller-&gt;filterEmptyFields($edu, 'education');

if (empty($checkEdu)) {
    $hook-&gt;setValue('education', null);
}

return true;
</code></pre>

Again, this is related to a dynamic form, which would have a numeric key at the end of a multi-dimensional array.

**Comment by goldsky** [comment]
the above example has been updated with the additional suffix property

**Comment by gadgetto** [comment]
@goldsky 

> Persistent Issue
> 
> I still can't find how to deal with checkbox, since when the $_POST is sent, the checkbox's name will not be available >if it is not checked.
> Can be done with UpdateProfile's preHook.

I solved this by adding an input type hidden with the name of the checkboxfield and empty value to the form.

`<input type="hidden" name="fieldname[]" value="">`

So if no checkbox is selected the form will  at least post an empty value.

**Comment by goldsky** [comment]
@gadgetto 
and if it is checked? might be another JS work?
I believe order matters in this case.

**Comment by jpdevries** [comment]
@goldsky I don't want this to get ignored (any longer). I'm working on merging changes into a new repo at modxcms/Login but am going to need to come back to review this one.

**Comment by goldsky** [comment]
@jpdevries excellent!

**Pull request closed without merging**
